import "../app/globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import NavLogo3 from "../public/assets/navLogo3.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Peters_RESUME",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/assets/navLogo3.png" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
