// import "../../app/globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

// Layout.js

import { useEffect } from "react";
import { useRouter } from "next/router";
import { Inter } from "next/font/google";
import Head from "next/head";
import "../app/globals.css"; // Import global styles from globals.css

const inter = Inter({ subsets: ["latin"] });

const Layout = ({ children }) => {
  const router = useRouter();

  useEffect(() => {
    // Scroll to top on route change
    const handleRouteChange = () => {
      window.scrollTo(0, 0);
    };

    router.events.on("routeChangeComplete", handleRouteChange);

    return () => {
      router.events.off("routeChangeComplete", handleRouteChange);
    };
  }, [router]);

  return (
    <>
      <Head>
        {/* Include Google Fonts link for Playfair Display SC */}
        <link
          href="https://fonts.googleapis.com/css2?family=Playfair+Display+SC:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      {/* Apply Playfair font family to all children */}
      <div
        className=" font-playfair"
        style={{ fontFamily: "'Playfair Display SC', serif" }}
      >
        {children}
      </div>
    </>
  );
};

export default Layout;
